include themes/dracula/kitty-master/dracula.conf

background #1c1c1c

term xterm-256color

font_family JetBrainsMono Nerd Font
font_size 12.0
modify_font cell_height -2px

text_composition_strategy legacy

cursor_shape block
shell_integration no-cursor

tab_bar_edge top
tab_bar_style separator

map shift+enter send_text all \x1b\r

