---
- name: Install utilities
  become: true
  ansible.builtin.apt:
    name: "{{ install_utils_packages }}"
    state: present
    update_cache: true

- name: Create bat config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/bat"
    state: directory
    mode: "0755"

- name: Copy bat config file
  ansible.builtin.copy:
    content: |
      --theme=Dracula
    dest: "{{ ansible_env.HOME }}/.config/bat/config"
    mode: "0644"
    backup: true

- name: Configure utility aliases in bash
  become: false
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "{{ item }}"
    state: present
  loop:
    - "alias fd='fdfind'"
    - "alias cat='batcat'"

- name: Install clipboard helpers script
  ansible.builtin.copy:
    src: clipboard.sh
    dest: "{{ ansible_env.HOME }}/.bash_clipboard"
    mode: "0644"
    backup: true

- name: Source clipboard helpers from bash
  become: false
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "source ~/.bash_clipboard"
    state: present
