gui:
  theme:
    activeBorderColor:
      - "#ff79c6"
      - bold
    inactiveBorderColor:
      - "#bd93f9"
    optionsTextColor:
      - "#6272a4"
    selectedLineBgColor:
      - "#44475a"
    cherryPickedCommitBgColor:
      - "#6272a4"
    cherryPickedCommitFgColor:
      - "#bd93f9"
    unstagedChangesColor:
      - "#ff5555"
    defaultFgColor:
      - "#f8f8f2"
git:
  paging:
    colorArg: always
    pager: delta --paging=never
