---
- name: Install tmux
  become: true
  ansible.builtin.apt:
    name:
      - tmux
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Copy tmux configuration file
  ansible.builtin.copy:
    src: tmux.conf
    dest: ~/.tmux.conf
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0644"

- name: Install tmux plugin manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    version: v3.1.0

- name: Install tmux plugins
  ansible.builtin.command: ~/.tmux/plugins/tpm/bin/install_plugins
  environment:
    TMUX_PLUGIN_MANAGER_PATH: ~/.tmux/plugins
  register: install_tmux_plugins_result
  changed_when: "'Installing' in install_tmux_plugins_result.stdout"
