---
- name: Copy scripts
  become: true
  ansible.builtin.copy:
    src: "scripts/"
    dest: "/usr/local/bin/"
    mode: "0755"

- name: Add quick-run alias to bash
  become: false
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "alias qr='quick-run'"
    state: present
