---
- name: Add Kubernetes apt repository
  become: true
  ansible.builtin.deb822_repository:
    name: kubernetes
    uris: https://pkgs.k8s.io/core:/stable:/v{{ install_infrastructure_tools_kubectl_version }}/deb/
    suites: "/"
    signed_by: https://pkgs.k8s.io/core:/stable:/v{{ install_infrastructure_tools_kubectl_version }}/deb/Release.key

- name: Install kubectl
  become: true
  ansible.builtin.apt:
    name: kubectl
    state: present
    update_cache: true
