name: Package collection

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  package:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Initialize uv environment
        run: uv sync

      - name: Validate collection build
        run: uv run ansible-galaxy collection build --output-path dist

